image: docker:latest

services:
  - docker:dind

before_script:
  - apk update && apk add make git

build-validate:
  stage: build
  script:
    - make REGISTRY_IMAGE="$CI_REGISTRY_IMAGE" REGISTRY_IMAGE_TAG="$CI_REGISTRY_IMAGE_TAG" image
  except:
    - /^release\/.*$/

build-push:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - VERSION=$(echo $CI_COMMIT_REF_NAME | sed "s:release/::g")
    - make REGISTRY_IMAGE="$CI_REGISTRY_IMAGE" image
    - docker push "$CI_REGISTRY_IMAGE:$VERSION"
  only:
    - /^release\/.*$/
  except:
    - branches
