image: docker:latest

services:
  - docker:dind

build-validate:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
  except:
    - /^release\/.*$/

build-push:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - RELEASE=$(echo $CI_COMMIT_REF_NAME | sed "s:release/::g")
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$RELEASE" .
    - docker push "$CI_REGISTRY_IMAGE:$RELEASE"
  only:
    - /^release\/.*$/
  except:
    - branches
