image: golang:1.11.4

services:
  - docker:dind

before_script:
  - mkdir -p /go/src/gitlab.com/frozy.io
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/frozy.io
  - make deps

build-validate:
  stage: build
  script:
    - make build
    - make test
  except:
    - /^release\/.*$/

build-push:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - VERSION=$(echo $CI_COMMIT_REF_NAME | sed "s:release/::g")
    - make REGISTRY_IMAGE="$CI_REGISTRY_IMAGE" image
    - docker push "$CI_REGISTRY_IMAGE:$VERSION"
  only:
    - /^release\/.*$/
  except:
    - branches
