language: go
go:
- 1.12.0
env:
- GO111MODULE=on
addons:
  apt:
    packages:
    - zip
go_import_path: gitlab.com/frozy.io/connector
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: fZB5VZORRKTiLbZuFJqkRK6d0bQrd5xJerJBpkFFDsHhTp21pSAcallFEVFhHPAwkY1zDUVezmosFF2Liy2M03slhR7u1sx91HuOm4Sv4C/IvUeKNsNiSO+D8IlB9ZOXbCAaeYa8MM6nys9iGqonaCs6DU5fRBi6yq1/qB8X6ADlSCCaOUilVxZoJN08lodXpUxnzzvIr6KGMcHXH4h9LyiFJtv/ticEwIZqy6VM7FAiHZrfH8QaNN61d9uk2+HXqeFI8sYTcjpSN0L2IU4YmFhSkpWP6Pa0jWrupsnjp4vF16Y2GnQ7ZUM1IDJCzSexdYUuuP1oosWV9ySKGMJupbPAyodtazpdfeoJyVbsdCSk+oWvry9cj9sK4yoEUcgQXB+5DoTP/Qdd5/agnEFk9yvR0tExdr+nqwMWT7JAijKae9I+IaM7NM9qknMZFGH12ZHjOoVnJjpcwJY+2dDIIDmgA+/wHnofBdXizKH4LyJo320llYzwycVfQOyb8W6Lm06p/zye5N6EXaXoAppuM3N2SKjzLfayioJttUWkqEfu2qiRP7DB0csh0PWAlbctcF7ZUfDq2d97hqw+xG5HKgui4jBvihjix7EelstTclnO9V6nwGDaH+bijLMUNSAdPU0u6nYbHM92W5C5mEmpruc6vremwd1NNJz38O2QO0A=
